### PR TITLE
import socket. fixes issue when socket isn't defined.

### PR DESCRIPTION
**Pull request by zachlatta**

### CODE REVIEW

**Comment by virtuald** [comment]
Thanks for the fix. Check out https://github.com/robotpy/pyfrc for a better integrated solution for uploading code to the robot.

**Comment by zachlatta** [comment]
Woah, that's awesome! Today we were messing around with our cRIO to get unit testing setup. Thanks for the tip!

**Comment by zachlatta** [comment]
@virtuald Out of curiosity, is there a recommended way to do live code-reloading? Right now we're just manually reloading modules and reinstantiating as needed.

**Comment by virtuald** [comment]
Currently, reloading the robot for us uses pyfrc, and takes the form of "./robot.py upload", which uploads the code and then reboots the robot. Since it only takes ~30s, it's not as bad as it could be. 

However, we don't do any live code-reloading. It would be nice to have, but I haven't looked at it. Originally RobotPy supported a form of live reloading, but it was taken out because it was buggy or something.

**Pull request merged**
